### PR TITLE
Support GHC 7.10

### PR DESCRIPTION
**Pull request by joachifm**

### CODE REVIEW

**Comment by joachifm** [comment]
Ach, I don't understand why this fails. Built just fine on my fork https://travis-ci.org/joachifm/saltine/builds/56371727

**Comment by tel** [comment]
I'm not sure either. I'm more than happy to accept this patch along with anything that can fix the Travis tech.

**Comment by tel** [comment]
I thought it was the Travis cache, but there doesn't appear to be one. It's been a while since I've used Travis in Haskell, though. Perhaps the new Halcyon stuff from mietek would work better?

**Comment by joachifm** [comment]
On Mon, Mar 30, 2015, at 09:17 PM, Joseph Abrahamson wrote:
> I thought it was the Travis cache, but there doesn't appear to be one.

I believe caching is a premium feature. Lack of caching makes free
travis quite susceptible to transient failures. Could you please try
restarting the build? I just did on my fork, and it once again built
successfully.

> It's been a while since I've used Travis in Haskell, though. Perhaps the
> new Halcyon stuff from mietek would work better?

I don't know, it looks cool, though.

**Comment by tel** [comment]
Restarted!

**Comment by joachifm** [comment]
Success this time. I've added an additional patch which I hope will improve robustness to unrelated transient failures.

**Pull request merged**
